environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

matrix:
  fast_finish: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build: off

test_script:
  - yarn lint
  - yarn test

version: "{build}"
